# https://taskfile.dev

version: "3"

vars:
  # Default values that can be overridden by .env file
  IMAGE_NAME: '{{default "postgres-wal-g" .IMAGE_NAME}}'
  IMAGE_TAG: '{{default "local-dev" .IMAGE_TAG}}'
  IMAGE_FULL_NAME: "{{.IMAGE_NAME}}:{{.IMAGE_TAG}}"
  POSTGRES_VERSION: '{{default "17.4" .POSTGRES_VERSION}}'
  WAL_G_VERSION: '{{default "v.3.0.7" .WAL_G_VERSION}}'
  TEST_POSTGRES_PORT: '{{default "5432" .TEST_POSTGRES_PORT}}'

env:
  DOCKER_BUILDKIT: "1"
  # Import environment variables from .env file if it exists

dotenv: [".env"]

tasks:
  default:
    cmds:
      - task -l

  build:
    desc: "Build the Docker image"
    cmds:
      - |
        docker buildx build \
          -t {{ .IMAGE_FULL_NAME }} \
          --build-arg POSTGRES_VERSION={{ .POSTGRES_VERSION }} \
          --build-arg WAL_G_VERSION={{ .WAL_G_VERSION }} \
          --load \
          .

  lint:
    desc: "Run linter"
    cmds:
      - hadolint Dockerfile

  test:
    desc: "Run container structure tests"
    deps:
      - build
    cmds:
      - container-structure-test test --image {{.IMAGE_NAME}}:{{.IMAGE_TAG}} --config structure-tests.yaml

  run:
    desc: "Run the Docker container"
    cmds:
      - |
        docker run -d --rm -it \
          -e POSTGRES_PASSWORD=postgres \
          -p {{.TEST_POSTGRES_PORT}}:5432 \
          {{ .IMAGE_FULL_NAME }}
