name: CI

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"
    paths:
      - "Dockerfile"
      - ".github/workflows/ci.yml"
      - ".github/actions/**"
      - "wal-g/**"
  workflow_dispatch:

env:
  CONTAINER_STRUCTURE_TESTS_VERSION: "1.19.3"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  # TODO maybe generate matrix based on input on workflow_dispatch
  test:
    name: Test with Postgres ${{ matrix.postgres_version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        postgres_version: ["17", "16"]
        wal_g_version: ["v3.0.7"]
      fail-fast: true
    env:
      IMAGE_NAME: "ghcr.io/brpaz/docker-postgres-wal-g:postgres-wal-g"
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set release tag
        id: set-release-tag
        run: |
          SHORT_SHA=${GITHUB_SHA::7}
          echo "RELEASE_IMAGE_TAG=${IMAGE_NAME}:${POSTGRES_VERSION}-${BUILD_NUMBER}-${SHORT_SHA}" >> $GITHUB_ENV
        env:
          IMAGE_NAME: ${{ env.IMAGE_NAME }}
          POSTGRES_VERSION: ${{ matrix.postgres_version }}
          BUILD_NUMBER: ${{ github.run_number }}

      - name: Lint Dockerfile
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: Dockerfile

      - uses: ./.github/actions/build-test
        id: build-test
        with:
          postgres_version: ${{ matrix.postgres_version }}
          wal_g_version: ${{ matrix.wal_g_version }}
          image_tag: ${{ env.RELEASE_IMAGE_TAG }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push Docker image
        uses: docker/build-push-action@v5
        if: github.event_name != 'pull_request'
        with:
          context: .
          tags: ${{ env.RELEASE_IMAGE_TAG }}
          push: true
          load: false
