name: CI

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"
  release:
    types: [published]

env:
  RELEASE_IMAGE_NAME: docker-image-template
  TEST_IMAGE_TAG: "app:test"
  CONTAINER_STRUCTURE_TESTS_VERSION: "1.19.3"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Lint Dockerfile
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: Dockerfile

      - name: Setup structure tests
        run: |
          curl -LO ${{ env.DOWNLOAD_URL}} && \
          chmod +x container-structure-test-linux-amd64 && \
          sudo mv container-structure-test-linux-amd64 /usr/local/bin/container-structure-test && \
          container-structure-test version
        env:
          DOWNLOAD_URL: https://github.com/GoogleContainerTools/container-structure-test/releases/download/v${{env.CONTAINER_STRUCTURE_TESTS_VERSION}}/container-structure-test-linux-amd64

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/brpaz/${{ env.RELEASE_IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}

      - name: Build test image
        uses: docker/build-push-action@v5
        with:
          context: .
          tags: ${{ env.TEST_IMAGE_TAG }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            BUILD_DATE=${{ fromJSON(steps.meta.outputs.json).labels['org.opencontainers.image.created'] }}
            VERSION=${{ fromJSON(steps.meta.outputs.json).labels['org.opencontainers.image.version'] }}
            REVISION=${{ fromJSON(steps.meta.outputs.json).labels['org.opencontainers.image.revision'] }}
          push: false
          load: true

      - name: Run image structure tests
        run: |
          container-structure-test test --image ${{ env.TEST_IMAGE_TAG }} --config structure-tests.yaml

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build final image
        uses: docker/build-push-action@v5
        if: github.event_name == 'release' || github.event_name == 'push' && github.ref == 'refs/heads/main'
        with:
          context: .
          tags: ${{ steps.meta.outputs.tags }}
          platforms: linux/amd64,linux/arm64
          push: true
