name: CI

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"
env:
  CONTAINER_STRUCTURE_TESTS_VERSION: "1.19.3"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Test ${{ matrix.postgres_version }}-wal-g-${{ matrix.wal_g_version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - postgres_version: "17"
            wal_g_version: "v3.0.7"
          - postgres_version: "16"
            wal_g_version: "v3.0.7"
    env:
      TEST_IMAGE_TAG: "ghcr.io/brpaz/postgres-wal-g:${{ matrix.postgres_version }}-${{ github.sha }}"
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Lint Dockerfile
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: Dockerfile

      - uses: ./.github/actions/build-test
        id: build-test
        with:
          postgres_version: ${{ matrix.postgres_version }}
          wal_g_version: ${{ matrix.wal_g_version }}
          image_tag: ${{ env.TEST_IMAGE_TAG }}
